version: "3.4"
services:
  nginxProxy:
    build:
      context: .
      target: nginxProxy
    ports:
      - "9000:9000"
    restart: always
  nginx:
    depends_on:
      - nginxProxy
    image: nginx:alpine
    restart: always
  usersApp:
    build:
      context: .
      target: usersApp
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGO=${JWT_ALGO}
      - PORT=5000
    depends_on:
      - nginxProxy
    container_name: 'users-service'
  settingsApp:
    build:
      context: .
      target: settingsApp
    ports:
      - "5001:5001"
    depends_on:
      - nginxProxy
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGO=${JWT_ALGO}
      - PORT=5001
    container_name: 'settings-service'
  tasksApp:
    build:
      context: .
      target: tasksApp
    ports:
      - "5002:5002"
    depends_on:
      - nginxProxy
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGO=${JWT_ALGO}
      - PORT=5002
    container_name: 'tasks-service'
